### ISSUE TITLE
Shellcheck

### ISSUE THREAD

**Issue by lorenzleutgeb** [GitAlias/gitalias#105]
I wrote a script (see below) to run all (shell-interpreted) aliases through [Shellcheck](https://github.com/koalaman/shellcheck). See the [output at Seashells](https://seashells.io/v/sn7SFwqD). If it's expired, see [`output.txt`](https://github.com/GitAlias/gitalias/files/13053577/output.txt) (which contains ANSI escape codes, use `cat` to get colors). There are quite a lot of things to fix, and in my opinion it would be worth to automatically run Shellcheck on pull requests.

 1. Would you accept a PR fixing the issues that Shellcheck currently finds?
 2. Would you accept a PR to set up GitHub Actions to run Shellcheck on new PRs?

<details>
<summary>Script</summary>

```bash
#! /usr/bin/env bash

if [ $# == 1 ]
then
    REV="$1"
else
    REV=main
fi

curl --location "https://github.com/GitAlias/gitalias/raw/${REV}/gitalias.txt" |
git config --file=- --null --list |
while read -r -d $'\n' key
do
    # Remove prefix 'alias.'
    key=${key:6}

    read -r -d $'\0' value

    if [[ $value != !* ]]
    then
        printf "%s ――――  SKIP : %24s%s\n" "$(tput setaf 4)" "$key" "$(tput sgr0)"
        continue
    fi

    printf "%s ―――― CHECK : %24s%s\n" "$(tput setaf 6)" "$key" "$(tput sgr0)"
    shellcheck --shell=bash --color=always - <<< "${value:1}"
done
```

</details>

**Comment by joelparkerhenderson** [comment]
Yes. You know what you're doing. And also, would you like full access to the repo as a contributor?

**Comment by joelparkerhenderson** [comment]
A few quick notes for things in the repo and organization that may not be obvious from the existing code...

- The `echo` command has historically been problematic in practice on some of my clients' systems. I prefer `printf` with a template string then variables. Anything you wish to fix about these too is great.

- There's large userbase need for POSIX with sh, rather than anything specific to bash or zsh. If there's anything that needs more complexity than POSIX and sh, I generally favor moving the logic into a separate tool such as a python script or rust crate. The idea of leveraging separate tools is a potential way to add more capabilties to gitalias. 

- For POSIX sh, some of the techniques look strange if you're not familiar with them. I maintain a shell guide and utility functions file that I use with a bunch of organizations. I'm not an expert; the repos are what seems to have worked best among many of my consulting clients. If you're interested, see https://github.com/SixArm/unix-shell-script-kit and https://github.com/SixArm/unix-shell-script-tactics (and you're welcome to have member access to these too, if you wish).
 
- There's a huge area for improvement overall by creating tests. Even simple tests would be a big improvement. I've heard good things about ShellSpec (https://shellspec.info/) though I haven't tried it myself.

- The gitalias file has historically worked best as one big file, so it can be downloaded with one click. That said, there's a better approach (IMHO) that assembles the file from parts. For example, you can imagine that each alias function becomes its own real shell script, such that it can be shellchecked separately, then concatenated into the big file. 

Thank you!
